module.exports = {
  TREEHERDER_URL: 'https://treeherder.mozilla.org',
  TASKCLUSTER_TOOLS_URL: 'https://tools.taskcluster.net',
  AUTH0: {
    domain: 'auth.mozilla.auth0.com',
    clientID: '2dXygwTNP3p7iLTSaEWbdoiJFkjSBqm4',
    redirectUri: new URL('/login', window.location).href,
    scope: 'full-user-credentials openid profile email',
  },
  PRODUCTS: [
    {
      product: 'firefox',
      prettyName: 'Firefox Desktop',
      appName: 'browser',
      branches: [
        {
          prettyName: 'Beta',
          project: 'mozilla-beta',
          branch: 'releases/mozilla-beta',
          repo: 'https://hg.mozilla.org/releases/mozilla-beta',
          enableReleaseEta: false,
        },
        {
          prettyName: 'Release',
          project: 'mozilla-release',
          branch: 'releases/mozilla-release',
          repo: 'https://hg.mozilla.org/releases/mozilla-release',
          enableReleaseEta: true,
          rcBranch: 'releases/mozilla-beta',
          rcBranchVersionPattern: /b/,
          rcRepo: 'https://hg.mozilla.org/releases/mozilla-beta',
          numberOfPartials: 4,
        },
        {
          prettyName: 'ESR60',
          project: 'mozilla-esr60',
          branch: 'releases/mozilla-esr60',
          repo: 'https://hg.mozilla.org/releases/mozilla-esr60',
          enableReleaseEta: true,
          numberOfPartials: 5,
        },
        {
          prettyName: 'ESR68',
          project: 'mozilla-esr68',
          branch: 'releases/mozilla-esr68',
          repo: 'https://hg.mozilla.org/releases/mozilla-esr68',
          enableReleaseEta: true,
          numberOfPartials: 5,
          alternativeBranch: 'releases/mozilla-esr60',
        },
      ],
      enablePartials: true,
    },
    {
      product: 'fennec',
      prettyName: 'Firefox Mobile',
      // TODO: The actual appName is `mobile/android` but it gets the version from `browser`.
      appName: 'browser',
      branches: [
        {
          prettyName: 'Beta',
          project: 'mozilla-esr68',
          branch: 'releases/mozilla-esr68',
          repo: 'https://hg.mozilla.org/releases/mozilla-esr68',
          enableReleaseEta: false,
          productKey: 'fennec_beta',
          versionFile: 'mobile/android/config/version-files/beta/version_display.txt',
        },
        {
          prettyName: 'Release',
          project: 'mozilla-release',
          branch: 'releases/mozilla-release',
          repo: 'https://hg.mozilla.org/releases/mozilla-release',
        },
      ],
      enablePartials: false,
    },
    {
      product: 'devedition',
      prettyName: 'Firefox Developer Edition',
      appName: 'browser',
      branches: [
        {
          prettyName: 'Beta',
          project: 'mozilla-beta',
          branch: 'releases/mozilla-beta',
          repo: 'https://hg.mozilla.org/releases/mozilla-beta',
          enableReleaseEta: false,
        },
      ],
      enablePartials: true,
    },
    {
      product: 'thunderbird',
      prettyName: 'Thunderbird',
      appName: 'mail',
      branches: [
        {
          prettyName: 'Beta',
          project: 'comm-beta',
          branch: 'releases/comm-beta',
          repo: 'https://hg.mozilla.org/releases/comm-beta',
          enableReleaseEta: false,
        },
        {
          prettyName: 'ESR60',
          project: 'comm-esr60',
          branch: 'releases/comm-esr60',
          repo: 'https://hg.mozilla.org/releases/comm-esr60',
          enableReleaseEta: false,
        },
        {
          prettyName: 'ESR68',
          project: 'comm-esr68',
          branch: 'releases/comm-esr68',
          repo: 'https://hg.mozilla.org/releases/comm-esr68',
          enableReleaseEta: false,
        },
      ],
      enablePartials: false,
    },
  ],
};
