version: 0
allowPullRequests: public
metadata:
  name: "Mozilla RelEng"
  description: "Mozilla RelEng Services"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:

  - metadata:
      name: "0. Decision task"
      description: "A task that detects changes and rebuilds application that needs to be rebuilt."
      owner: "{{ event.head.user.email }}"
      source: "https://github.com/mozilla-releng/services/tree/taskcluster-rework"
    routes:
      - index.project.releng.services.requests.{{ event.head.repo.branch }}.by-timestamp.{{ timestamp }}
      - index.project.releng.services.requests.{{ event.head.repo.branch }}.by-revision.{{ event.head.sha }}
    scopes:
      - secrets:get:repo:github.com/mozilla-releng/services:branch:taskcluster-rework
      - assume:hook-id:project-releng/services-taskcluster-rework-*
      - hooks:modify-hook:project-releng/services-taskcluster-rework-*
      - queue:create-task:aws-provisioner-v1/releng-task
      - queue:route:index.project.releng.services.requests.{{ event.head.repo.branch }}.*
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
        branches:
          - taskcluster-rework
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1800  # 30min
      image: "mozillareleng/services:base-latest"
      features:
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "-c"
        - "cd /tmp && wget https://github.com/mozilla-releng/services/archive/$GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd services-$GITHUB_HEAD_SHA && env && rm -rf /root/.cache/nix && ./please -vv tools decision-task"
