"""empty message

Revision ID: 0e3855e1d130
Revises: 3a54bd40145f
Create Date: 2016-11-02 15:55:59.966833

"""

# revision identifiers, used by Alembic.
revision = '0e3855e1d130'
down_revision = '3a54bd40145f'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipit_dashboard_contributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bugzilla_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('avatar_url', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bugzilla_id')
    )
    op.create_table('shipit_dashboard_contributor_bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('bug_id', sa.Integer(), nullable=True),
    sa.Column('roles', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['shipit_dashboard_bug.id'], ),
    sa.ForeignKeyConstraint(['contributor_id'], ['shipit_dashboard_contributor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contributor_id', 'bug_id', name='uniq_contrib_bug')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipit_dashboard_contributor_bugs')
    op.drop_table('shipit_dashboard_contributor')
    ### end Alembic commands ###
