"""empty message

Revision ID: 1eb1ce61f03e
Revises: 85ee332dd4db
Create Date: 2017-02-08 16:37:06.437732

"""

# revision identifiers, used by Alembic.
revision = '1eb1ce61f03e'
down_revision = '85ee332dd4db'

import sqlalchemy as sa
from alembic import op

TABLE = 'shipit_dashboard_analysis'

def upgrade():

    # Add nullable version
    op.add_column(TABLE, sa.Column('version', sa.Integer(), nullable=True))

    # Declare pseudo table for alembic usage
    analysis = sa.sql.table(TABLE,
        sa.sql.column('id'),
        sa.sql.column('name'),
        sa.sql.column('version'),
    )

    # Update data for analysis
    updates = (
        (1, 'aurora', 53),
        (2, 'beta', 52),
        (3, 'release', 51),
        (4, 'esr', 45),
    )
    for analysis_id, name, version in updates:
        op.execute(
            analysis.update() \
            .where(analysis.c.id==analysis_id) \
            .values({
                'name': name,
                'version': version,
            })
        )

    # Set version & name as non nullable
    op.alter_column(TABLE, 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column(TABLE, 'version',
               existing_type=sa.INTEGER(),
               nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(TABLE, 'version')
    op.alter_column(TABLE, 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
