"""empty message

Revision ID: 85ee332dd4db
Revises: 2158e8a5b554
Create Date: 2016-12-09 11:29:54.961057

"""

# revision identifiers, used by Alembic.
revision = '85ee332dd4db'
down_revision = '2158e8a5b554'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipit_dashboard_contributor', sa.Column('comment_private', sa.Text(), nullable=True))
    op.add_column('shipit_dashboard_contributor', sa.Column('comment_public', sa.Text(), nullable=True))
    op.add_column('shipit_dashboard_contributor', sa.Column('karma', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipit_dashboard_contributor', 'karma')
    op.drop_column('shipit_dashboard_contributor', 'comment_public')
    op.drop_column('shipit_dashboard_contributor', 'comment_private')
    # ### end Alembic commands ###
