"""empty message

Revision ID: e589b0fe9ef5
Revises: 1eb1ce61f03e
Create Date: 2017-02-09 10:30:19.623224

"""

# revision identifiers, used by Alembic.
revision = 'e589b0fe9ef5'
down_revision = '1eb1ce61f03e'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipit_dashboard_patch_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.String(length=50), nullable=False),
    sa.Column('revision_parent', sa.String(length=50), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('merged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['shipit_dashboard_bug.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bug_id', 'revision', 'revision_parent', 'branch', name='uniq_patch_status')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipit_dashboard_patch_status')
    # ### end Alembic commands ###
