"""empty message

Revision ID: 2158e8a5b554
Revises: 0e3855e1d130
Create Date: 2016-12-01 12:15:59.531773

"""

# revision identifiers, used by Alembic.
revision = '2158e8a5b554'
down_revision = '0e3855e1d130'

from alembic import op


def upgrade():
    def _create_constraint(sql_op):
        sql_op.create_unique_constraint(
            'shipit_dashboard_uniq_ba',
            'shipit_dashboard_analysis_bugs',
            ['analysis_id', 'bug_id'],
        )

    try:
        # Works on Potsgresql (Heroku & dev)
        _create_constraint(op)
    except NotImplementedError:
        # Works on sqlite (unit tests)
        _create_constraint(op.batch_alter_table('shipit_dashboard_analysis_bugs'))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shipit_dashboard_uniq_ba', 'shipit_dashboard_analysis_bugs', type_='unique')
    ### end Alembic commands ###
