"""empty message

Revision ID: 46d559f516ea
Revises: e589b0fe9ef5
Create Date: 2017-02-17 10:52:04.931096

"""

# revision identifiers, used by Alembic.
revision = '46d559f516ea'
down_revision = 'e589b0fe9ef5'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipit_dashboard_patch_status', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipit_dashboard_patch_status', 'message')
    # ### end Alembic commands ###
