# This file has been generated by node2nix 1.1.1. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x"}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv utillinux runCommand writeTextFile;
    python = pkgs.python2;inherit nodejs;
  };
in
import ./node-modules-generated.nix {
  inherit (pkgs) fetchurl fetchgit;
  inherit nodeEnv;
}