"""empty message

Revision ID: 2158e8a5b554
Revises: 0e3855e1d130
Create Date: 2016-12-01 12:15:59.531773

"""

# revision identifiers, used by Alembic.
revision = '2158e8a5b554'
down_revision = '0e3855e1d130'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('shipit_dashboard_uniq_ba', 'shipit_dashboard_analysis_bugs', ['analysis_id', 'bug_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shipit_dashboard_uniq_ba', 'shipit_dashboard_analysis_bugs', type_='unique')
    ### end Alembic commands ###
