# This file has been generated by node2nix 1.0.0. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python utillinux runCommand writeTextFile;
    nodejs = pkgs."nodejs-6_x";
  };
in
import ./node-modules-generated.nix {
  inherit (pkgs) fetchurl fetchgit;
  inherit nodeEnv;
}